# ROS-Gazebo Bridge Configuration
- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- ros_topic_name: /sim/imu_raw
  gz_topic_name: /sim/imu_raw
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /world/state
  gz_topic_name: /world/default/state
  ros_type_name: gz_msgs/msg/World
  gz_type_name: gz.msgs.World
  direction: GZ_TO_ROS
